version: '3.8'

services:
  BDD-mysql-test:
    image: mysql:8.3.0
    environment:
      - MYSQL_ROOT_PASSWORD=romerospring
      - MYSQL_DATABASE=db_jpa_spring
    container_name: BDD-TEST-SPRING
    volumes:
      - data-bdd:/var/lib/mysql
    restart: always
    ports:
      - 4000:3306

volumes:
  data-bdd: